Add `ILikeHandler`
yiisoft/data-cycle pull request #14
Opened 2024-04-05 09:21 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌

2024-05-01 13:46 UTC, vjik requested changes

2024-05-01 13:46 UTC, vjik commented on src/Reader/FilterHandler/ILikeHandler/ILikeHandlerFactory.php
> +    public static function getIlikeHandler(?DriverInterface $databaseDriver): FilterHandlerInterface
This method used in `EntityReader` only, maybe move it there as private?

2024-05-01 13:46 UTC, vjik commented on src/Reader/FilterHandler/ILikeHandler/ILikeHandlerFactory.php
> +        $driverType = $databaseDriver?->getType() ?? 'SQLite';
Is there case when database driver not exist?

2024-05-01 13:46 UTC, vjik commented on tests/Feature/Base/Reader/FilterHandler/LikeHandlerTest.php
> +            'case does not match' => ['email', 'SEED@%', [2]],
Should `like` always be case sensitive?

2024-10-03 13:18 UTC, arogachev commented
Replaced by #31.

2024-10-03 13:18 UTC, closed without merging